Repository digital-nomadd/Project-Everland, pull requests merged in 2023-01, with the labels that each got.

#33 fix: donation adaptivity
  blocks/donation/__values/donation__values.css
  blocks/donation/__wrapper/donation__wrapper.css
  blocks/donation/donation.css
Labels: fix

#34 refactor: button layout
  blocks/button/__text/button__text.css
  blocks/button/__wrapper/_full-width/button__wrapper_full-width.css
  blocks/button/__wrapper/button__wrapper.css
  blocks/button/_color/button_color_blue.css
  blocks/button/_color/button_color_green.css
  blocks/button/_color/button_color_orange.css
  blocks/button/_color/button_color_purple.css
  blocks/button/_full-width/button_full-width.css
  blocks/button/_place/button_place_down.css
  blocks/button/_type/button_type_donate.css
  blocks/button/_type/button_type_link.css
  blocks/button/_type/button_type_on-color.css
  blocks/button/_type/button_type_radio-dif.css
  blocks/button/_type/button_type_radio.css
  blocks/button/_type/button_type_secondary.css
  blocks/button/button.css
  index.html
  pages/index.css
Labels: refactor

#47 refactor: button sizing and roles
  blocks/button/__arrow/button__arrow.css
  blocks/button/_place/button_place_agency-down.css
  blocks/button/_type/button_type_accordeon.css
  blocks/button/_type/button_type_donate.css
  blocks/button/_type/button_type_link.css
  blocks/button/_type/button_type_radio-dif.css
  blocks/button/_type/button_type_radio.css
  blocks/button/_type/button_type_slider.css
  blocks/button/button.css
  images/button_plus_grey.svg
  index.html
Labels: refactor

#36 Refactor footer
  blocks/footer/__icon-support-container/footer__icon-support-container.css
  blocks/footer/__icon-support/footer__icon-support.css
  blocks/footer/__item-content/footer__item-content.css
  blocks/footer/__item-text/_align-self/footer__item-text_align-self.css
  blocks/footer/__item-text/_width-320/footer__item-text_width-320.css
  blocks/footer/__item-title/footer__item-title.css
  index.html
  pages/index.css
Labels: refactor

#48 Fix content overflow and add correct border-radius
  blocks/button/_type/_fix-sum/button_type_fix-sum.css
  blocks/button/_type/_rand-sum/button_type_rand-sum.css
  blocks/cards/__button/cards__button.css
  blocks/cards/__item/_type/cards__item_type_no-icon.css
  blocks/cards/__item/cards__item.css
  pages/index.css
Labels: refactor

#50 Moved double selectors from`_color` to `button__arrow`
  blocks/button/__arrow/button__arrow.css
  blocks/button/_color/button_color_blue.css
  blocks/button/_color/button_color_green.css
  blocks/button/_color/button_color_orange.css
  blocks/button/_color/button_color_purple.css
Labels: style

#53 Added radiobutton functionality to "donation"
  blocks/button/_type/button_type_radio-dif.css
  blocks/button/_type/button_type_radio.css
  index.html
  pages/index.css
Labels: refactor

#54 Radio buttons in "donation" connected to "support"
  scripts/script.js
Labels: enhancement

#43 Refactor section "digits"
  blocks/digits/__paragraph/digits__paragraph.css
  blocks/digits/__title/digits__title.css
  index.html
Labels: refactor

#46 Refactor section "specprojects"
  blocks/specprojects/__box/specprojects__box.css
  blocks/specprojects/__buttons-box/specprojects__buttons-box.css
  blocks/specprojects/__column/specprojects__column.css
  blocks/specprojects/__description/specprojects__description.css
  blocks/specprojects/__header/specprojects__header.css
  blocks/specprojects/__image/specprojects__image.css
  blocks/specprojects/__item/specprojects__item.css
  blocks/specprojects/__photo-mobile/specprojects__photo-mobile.css
  blocks/specprojects/specprojects.css
Labels: refactor

#56 Refactor/advantages
  blocks/advantages/__accordion/advantages__accordion.css
  blocks/advantages/__content/advantages__content.css
  blocks/advantages/__header/advantages__header.css
  blocks/advantages/__item/advantages__item.css
  blocks/advantages/__title/advantages__title.css
  blocks/advantages/advantages.css
  blocks/digits/__content/digits__content.css
  blocks/digits/__grid/digits__grid.css
  blocks/digits/__image/digits__image.css
  blocks/digits/__paragraph/digits__paragraph.css
  blocks/digits/__title-accent/digits__title-accent.css
  blocks/digits/__title/__title-accent/digits__title_accent.css
  blocks/digits/__title/digits__title.css
  blocks/digits/digits.css
  blocks/specprojects/__box/specprojects__box.css
  blocks/specprojects/__buttons-box/specprojects__buttons-box.css
  blocks/specprojects/__column/specprojects__column.css
  blocks/specprojects/__description/specprojects__description.css
  blocks/specprojects/__header/specprojects__header.css
  blocks/specprojects/__image/specprojects__image.css
  blocks/specprojects/__item/specprojects__item.css
  index.html
  pages/index.css
Labels: refactor

#55 Refactor "header" and "popup-menu"
  blocks/header/__button-headen/header__button-headen.css
  blocks/header/__buttons/header__buttons.css
  blocks/header/__content/header__content.css
  blocks/header/__logo/header__logo.css
  blocks/header/__menu-icon/header__menu-icon.css
  blocks/header/__span/header__span.css
  blocks/header/__wrapper/_popup/header__wrapper_popup.css
  blocks/header/__wrapper/header__wrapper.css
  blocks/header/header.css
  blocks/icon-menu/icon-menu.css
  blocks/main-text/main-text.css
  blocks/platform-button/platform-button.css
  blocks/popup-menu/__close/popup-menu__close.css
  blocks/popup-menu/__group/popup-menu__group.css
  blocks/popup-menu/__header/popup-menu__header.css
  blocks/popup-menu/__list/popup-menu__list.css
  blocks/popup-menu/__main/popup-menu__main.css
  blocks/popup-menu/__tablet/popup-menu__tablet.css
  blocks/popup-menu/__title/popup-menu__title.css
  blocks/popup-menu/__wrapper/popup-menu__wrapper.css
  blocks/popup-menu/_opened/popup-menu_opened.css
  blocks/project/__image-container-first/project__image-container-first.css
  blocks/project/__image-container-second/project__image-container-second.css
  blocks/project/__image/_first/project__image_first.css
  blocks/project/__image/_second/project__image_second.css
  blocks/project/__images/project__images.css
  blocks/project/__switcher-counter/project__switcher-counter.css
  blocks/project/__switcher/project__switcher.css
  blocks/project/__text-container/project__text-container.css
  blocks/project/__text-list/project__text-list.css
  blocks/project/__text/project__text.css
  blocks/project/__title-container/project__title-container.css
  blocks/project/__title/project__title.css
  blocks/project/__wrapper/project__wrapper.css
  blocks/title-text/title-text.css
  index.html
  pages/index.css
  scripts/script.js
Labels: refactor

#57 Refactor section "agency"
  blocks/cards/_agency/cards_agency.css
  blocks/cards/cards.css
  index.html
  pages/index.css
Labels: refactor

#58 Refactored section "histories"
  blocks/histories/__hero-cards-item/histories__hero-cards-item.css
  blocks/histories/__quote-icon/histories__quote-icon.css
  blocks/histories/__text-title/histories__text-title.css
  index.html
Labels: refactor

#65 Update documentation
  README.md
  docs/contribute.md
  docs/issue_template.md
  docs/pull_request_template.md
Labels: documentation

#66 Rename docs files
  README.md
  docs/CONTRIBUTING.md
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation
